### PR TITLE
Unity puppet app. 'Auth Enabled' toggle now dependent on 'App Center Enabled' toggle. 

### PR DESCRIPTION
**Pull request by olmisa**
Things to consider before you submit the PR:

* [ ] Has `CHANGELOG.md` been updated?
* [ ] Are tests passing locally?
* [x] Are the files formatted correctly?
* [ ] Did you add unit tests if this modifies the Windows code?
* [x] Did you test your change with either the sample apps that are included in the repository or with a blank app that uses your change?

## Description

'Child toggle' from 'Transmission' was set as 'Auth Enabled' toggle in PuppetAuth. 

## Misc

[AB#69748](https://msmobilecenter.visualstudio.com/454a20a9-dfe6-4c1f-8ae8-417f76adb472/_workitems/edit/69748)

### CODE REVIEW

**Review by annakocheshkova — DISMISSED** [review]

**Comment by MatkovIvan** [comment]
@olmisa Please resolve conflicts

**Review by MatkovIvan — COMMENTED** [review]
@olmisa Please resolve conflicts

**Comment by guperrot** [comment]
Template says it was not tested in app. Was it tested?

**Review by annakocheshkova — APPROVED** [review]

**Comment by olmisa** [comment]
Yes, it was tested.

**Pull request merged**
